import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'
import { resolve } from 'path'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      injectRegister: 'auto',
      // Custom SW (src/sw.ts): same caching as the old generateSW config PLUS
      // the Web Push listeners — generateSW cannot host push handlers.
      strategies: 'injectManifest',
      srcDir: 'src',
      filename: 'sw.ts',
      // Source icons live in public/ (generated by `npm run generate-pwa-assets`).
      includeAssets: ['favicon.svg', 'favicon.ico', 'apple-touch-icon-180x180.png'],
      manifest: {
        name: 'Wallet360 — Finanças pessoais',
        short_name: 'Wallet360',
        description: 'As tuas finanças, de todos os ângulos. Créditos, investimentos e orçamento num só sítio.',
        lang: 'pt-PT',
        display: 'standalone',
        start_url: '/',
        scope: '/',
        theme_color: '#0D2740',
        background_color: '#FAF9F7',
        icons: [
          { src: 'pwa-64x64.png', sizes: '64x64', type: 'image/png' },
          { src: 'pwa-192x192.png', sizes: '192x192', type: 'image/png' },
          { src: 'pwa-512x512.png', sizes: '512x512', type: 'image/png' },
          { src: 'maskable-icon-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
      },
      // Routing/caching behaviour lives in src/sw.ts now; this only controls
      // what gets injected into the precache manifest.
      injectManifest: {
        globPatterns: ['**/*.{js,css,html,svg,png,ico,woff2}'],
      },
      // Keep the SW out of the way during `npm run dev` (no caching surprises).
      devOptions: { enabled: false },
    }),
  ],
  build: {
    rollupOptions: {
      output: {
        // Split heavy vendors out of the monolithic app chunk so the browser can
        // fetch them in parallel and cache them across deploys (they change far
        // less often than app code). The PDF parser stays its own lazy chunk via
        // its dynamic import — manualChunks only affects statically-imported deps.
        manualChunks(id) {
          if (!id.includes('node_modules')) return
          if (id.includes('chart.js') || id.includes('react-chartjs-2')) return 'charts'
          if (id.includes('react-query')) return 'react-query'
          if (id.includes('react-router') || id.includes('@remix-run')) return 'router'
          if (id.includes('i18next') || id.includes('react-i18next')) return 'i18n'
          if (id.includes('/react/') || id.includes('react-dom') || id.includes('scheduler')) return 'react'
          return 'vendor'
        },
      },
    },
  },
  resolve: {
    alias: {
      '@': resolve(__dirname, 'src'),
    },
  },
  server: {
    port: 5173,
    proxy: {
      // Proxy /api calls to the Express backend during dev
      '/api': {
        target: 'http://localhost:4000',
        changeOrigin: true,
      },
    },
  },
})
